// Users
let users = [
  {
    userId: 1,
    email: 'admin@admin.com',
    password: '123',
    firstName: 'Mr Admin',
    lastName: 'Istrator',
    isAdmin: true,
    billingAddress: 'Important Building 123',
    shippingAddress: 'Not so Important Building 123',
  },
  {
    userId: 2,
    email: 'user@user.com',
    password: '123',
    firstName: 'User',
    lastName: 'Common',
    isAdmin: false,
    billingAddress: 'Common house 123',
    shippingAddress: 'Neighbours house 321',
  },
  {
    userId: 3,
    email: 'pharetra.nam@icloud.couk',
    password: 'CLU85YKG1IO',
    firstName: 'Elvis',
    lastName: 'Wagner',
    isAdmin: false,
    billingAddress: '250-8673 Lectus Ave',
    shippingAddress: '157-812 Nisl Road',
  },
  {
    userId: 4,
    email: 'taciti.sociosqu@aol.net',
    password: 'VUH43RDE7YE',
    firstName: 'Lucas',
    lastName: 'Gentry',
    isAdmin: false,
    billingAddress: 'P.O. Box 973, 6934 Fusce Av.',
    shippingAddress: '451-6556 Pellentesque St.',
  },
  {
    userId: 5,
    email: 'ac.urna@google.edu',
    password: 'KEA66UKB1YG',
    firstName: 'Ira',
    lastName: 'Moran',
    isAdmin: false,
    billingAddress: '231-5240 Tempor Ave',
    shippingAddress: 'P.O. Box 581, 4491 Accumsan Road',
  },
  {
    userId: 6,
    email: 'nec@icloud.net',
    password: 'ACQ37IVL9KO',
    firstName: 'Lynn',
    lastName: 'Guzman',
    isAdmin: true,
    billingAddress: '628-1737 Eu St.',
    shippingAddress: '315-4089 Elit, Rd.',
  },
  {
    userId: 7,
    email: 'tempor@google.net',
    password: 'LWF18IEV6MY',
    firstName: 'Audrey',
    lastName: 'Goodwin',
    isAdmin: true,
    billingAddress: 'Ap #100-8810 Tincidunt Rd.',
    shippingAddress: 'Ap #591-8039 Adipiscing. Rd.',
  },
];

module.exports = users;
